/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ForecastIdRouteImport } from './routes/forecast/$id'
import { Route as ForecastNewRouteImport } from './routes/forecast/new'
import { Route as ProfileAddressRouteImport } from './routes/profile/$address'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastIdRoute = ForecastIdRouteImport.update({
  id: '/forecast/$id',
  path: '/forecast/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastNewRoute = ForecastNewRouteImport.update({
  id: '/forecast/new',
  path: '/forecast/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAddressRoute = ProfileAddressRouteImport.update({
  id: '/profile/$address',
  path: '/profile/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/docs': typeof DocsRoute
  '/explore': typeof ExploreRoute
  '/leaderboard': typeof LeaderboardRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/forecast/$id': typeof ForecastIdRoute
  '/forecast/new': typeof ForecastNewRoute
  '/profile/$address': typeof ProfileAddressRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/docs': typeof DocsRoute
  '/explore': typeof ExploreRoute
  '/leaderboard': typeof LeaderboardRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/forecast/$id': typeof ForecastIdRoute
  '/forecast/new': typeof ForecastNewRoute
  '/profile/$address': typeof ProfileAddressRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/docs': typeof DocsRoute
  '/explore': typeof ExploreRoute
  '/leaderboard': typeof LeaderboardRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/forecast/$id': typeof ForecastIdRoute
  '/forecast/new': typeof ForecastNewRoute
  '/profile/$address': typeof ProfileAddressRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/docs'
    | '/explore'
    | '/leaderboard'
    | '/roadmap'
    | '/security'
    | '/forecast/$id'
    | '/forecast/new'
    | '/profile/$address'
    | '/api/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/docs'
    | '/explore'
    | '/leaderboard'
    | '/roadmap'
    | '/security'
    | '/forecast/$id'
    | '/forecast/new'
    | '/profile/$address'
    | '/api/v1/$'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/docs'
    | '/explore'
    | '/leaderboard'
    | '/roadmap'
    | '/security'
    | '/forecast/$id'
    | '/forecast/new'
    | '/profile/$address'
    | '/api/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  DocsRoute: typeof DocsRoute
  ExploreRoute: typeof ExploreRoute
  LeaderboardRoute: typeof LeaderboardRoute
  RoadmapRoute: typeof RoadmapRoute
  SecurityRoute: typeof SecurityRoute
  ForecastIdRoute: typeof ForecastIdRoute
  ForecastNewRoute: typeof ForecastNewRoute
  ProfileAddressRoute: typeof ProfileAddressRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast/$id': {
      id: '/forecast/$id'
      path: '/forecast/$id'
      fullPath: '/forecast/$id'
      preLoaderRoute: typeof ForecastIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast/new': {
      id: '/forecast/new'
      path: '/forecast/new'
      fullPath: '/forecast/new'
      preLoaderRoute: typeof ForecastNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$address': {
      id: '/profile/$address'
      path: '/profile/$address'
      fullPath: '/profile/$address'
      preLoaderRoute: typeof ProfileAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  DocsRoute: DocsRoute,
  ExploreRoute: ExploreRoute,
  LeaderboardRoute: LeaderboardRoute,
  RoadmapRoute: RoadmapRoute,
  SecurityRoute: SecurityRoute,
  ForecastIdRoute: ForecastIdRoute,
  ForecastNewRoute: ForecastNewRoute,
  ProfileAddressRoute: ProfileAddressRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
